### ISSUE TITLE
The requested DurationSeconds exceeds the MaxSessionDuration set for this role

### ISSUE THREAD

**Issue by thepatrick** [ruimarinho/gsts#13]
This script assumes that the value of `https://aws.amazon.com/SAML/Attributes/SessionDuration` is less than the value of `MaxSessionDuration` for all roles, which isn't true for my use case, which is multiple roles, but only the dev account allows up to 12 hour sessions (other roles have the default 1 hour limit).

[aws-google-auth](https://github.com/cevoaustralia/aws-google-auth) solved this by allowing the user to specify a command line argument / environment variable to specify the duration.

Would you be open to a PR that would allow specifying an override value for sessionDuration?

```
Parsed SAML assertion {
  attributes: [
    {
      name: 'https://aws.amazon.com/SAML/Attributes/RoleSessionName',
      value: [Array]
    },
    {
      name: 'https://aws.amazon.com/SAML/Attributes/Role',
      value: [Array]
    },
    {
      name: 'https://aws.amazon.com/SAML/Attributes/SessionDuration',
      value: [Array]
    }
  ]
}
Found SessionDuration attribute 28800
Found Role ARN arn:aws:iam::[account]:role/[role]
Found Principal ARN arn:aws:iam::[account]:saml-provider/[provider]
The requested DurationSeconds exceeds the MaxSessionDuration set for this role.
```

**Comment by ruimarinho** [comment]
Can you try updating to the latest version please?

**Comment by ruimarinho** [comment]
@thepatrick I was on mobile on my initial reply and now that I've re-read the issue, the latest version would not have fixed this issue (there was a SessionDuration improvement but not on this particular case).

This makes complete sense.

> Would you be open to a PR that would allow specifying an override value for sessionDuration?

Yes, absolutely. Thank you.

**Comment by thepatrick** [comment]
No worries, I was hoping I might have missed something 😄 

I'll do that.

**Comment by lizthegrey** [comment]
Just to link the threads together, the previously reported bug was: https://github.com/ruimarinho/gsts/issues/9

**Comment by ruimarinho** [comment]
@lizthegrey @thepatrick now that I believe I understand this issue a little bit better, I've taken a different approach. Instead of failing and forcing the user to fix the underlying problem, I'm fetching the IAM role's properties from the IAM service and making sure the `MaxSessionDuration` is never exceeded, while still warning the user about it:

<img width="823" alt="Screenshot 2020-04-24 at 01 31 48" src="https://user-images.githubusercontent.com/288709/80162475-5f2f1d80-85cb-11ea-928f-9a98273f55b4.png">

Please give `2.3.0-beta.1` on npm a try and let me know what you think!

**Comment by thepatrick** [comment]
That approach makes sense to me! Thank you for doing that :) 

Unfortunately when I try and use `2.3.0-beta.1` it hangs - logged separately as #15
