### ISSUE TITLE
Autopopulating email causes conflicts

### ISSUE THREAD

**Issue by lizthegrey** [ruimarinho/gsts#17]
https://share.getcloudapp.com/YEu1Xe1N

**Comment by ruimarinho** [comment]
Hi @lizthegrey,

Thanks for the bug report. I have also experienced this issue but I can't really attribute to anything in specific.. seems random to me. As it appears I am using the officially recommended puppeteer API for this, I would have to dig a lot deeper to understand what might be the root cause.

For now, I have switched to a workaround which seems to work according to some GitHub issues I've seen on their repo. Mostly related to missing text, but I suspect the underlying cause is related to the timing of the detection of the DOM element.

Please let me know if it improves or completely eliminates the issue, otherwise I might as well remove this feature if it doesn't offer a consistently good UX.

Released on `v2.3.0-beta.3`. As usual, install with `yarn global add gsts@2.3.0-beta.3`.
